x-logging:
  &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '1'
      max-size: '10m'
version: '3'

services:
  postgres:
    image: postgres # fix issues when upgrading using: mysql_upgrade -u root -p
    container_name: postgres
    <<: *x-logging
    restart: unless-stopped
    networks:
      - rede-default
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
  app:
    build: .
    restart: always
    <<: *x-logging
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    networks:
      - rede-default
    ports:
      - 8080:8080
  mongo:
    image: mongo:7.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - rede-default
    ports:
      - "27017:27017"
networks:
  rede-default:


volumes:
  mariadb:

    # compose up -d --no-build --remove-orphans
    # .\gradlew build -x test
